export const Data = [
  {
      "sno": 1,
      "natureOfActivity": "Nomination",
      "activity": "PF Compliance",
      "nameOfForm": "Form-2/E - nomination",
      "applicationLaw": "Provident Fund & Miscellaneous Act. 1952",
      "typeOfAct": "Central",
      "section":"data",
      "actualFillingFrequency": "NA",
      "lastFilledDate": "09-08-2024",
      "fillingFrequency": "NA",
  },
//   {
//       "sno": 2,
//       "natureOfActivity": "Registration",
//       "activity": "ESI Compliance",
//       "nameOfForm": "Form-1",
//       "applicationLaw": "Employee State Insurance Act. 1948",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "Monthly",
//       "lastFilledDate": "01-08-2024",
//       "fillingFrequency": "Monthly",
//   },
//   {
//       "sno": 3,
//       "natureOfActivity": "Nomination",
//       "activity": "PF Compliance",
//       "nameOfForm": "Form-2/E - nomination",
//       "applicationLaw": "Provident Fund & Miscellaneous Act. 1952",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "NA",
//       "lastFilledDate": "09-08-2024",
//       "fillingFrequency": "NA",
//   },
//   {
//       "sno": 4,
//       "natureOfActivity": "Filing",
//       "activity": "Labour Welfare Fund",
//       "nameOfForm": "Form-A",
//       "applicationLaw": "Labour Welfare Fund Act",
//       "typeOfAct": "State",
//       "section":"data",
//       "actualFillingFrequency": "Annually",
//       "lastFilledDate": "12-07-2024",
//       "fillingFrequency": "Annually",
//   },
//   {
//       "sno": 5,
//       "natureOfActivity": "Return",
//       "activity": "Professional Tax",
//       "nameOfForm": "Form-II",
//       "applicationLaw": "Professional Tax Act",
//       "typeOfAct": "State",
//       "section":"data",
//       "actualFillingFrequency": "Half-Yearly",
//       "lastFilledDate": "15-06-2024",
//       "fillingFrequency": "Half-Yearly",
//   },
//   {
//       "sno": 6,
//       "natureOfActivity": "Declaration",
//       "activity": "Gratuity Compliance",
//       "nameOfForm": "Form-F",
//       "applicationLaw": "Payment of Gratuity Act. 1972",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "NA",
//       "lastFilledDate": "20-05-2024",
//       "fillingFrequency": "NA",
//   },
//   {
//       "sno": 7,
//       "natureOfActivity": "Filing",
//       "activity": "Maternity Benefits",
//       "nameOfForm": "Form-MB",
//       "applicationLaw": "Maternity Benefit Act. 1961",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "NA",
//       "lastFilledDate": "30-07-2024",
//       "fillingFrequency": "NA",
//   },
//   {
//       "sno": 8,
//       "natureOfActivity": "Audit",
//       "activity": "PF Audit",
//       "nameOfForm": "Form-Audit",
//       "applicationLaw": "Provident Fund & Miscellaneous Act. 1952",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "Annually",
//       "lastFilledDate": "25-03-2024",
//       "fillingFrequency": "Annually",
//   },
//   {
//       "sno": 9,
//       "natureOfActivity": "Return",
//       "activity": "ESI Compliance",
//       "nameOfForm": "Form-R",
//       "applicationLaw": "Employee State Insurance Act. 1948",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "Quarterly",
//       "lastFilledDate": "10-07-2024",
//       "fillingFrequency": "Quarterly",
//   },
//   {
//       "sno": 10,
//       "natureOfActivity": "Compliance",
//       "activity": "Bonus Payment",
//       "nameOfForm": "Form-B",
//       "applicationLaw": "Payment of Bonus Act. 1965",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "Annually",
//       "lastFilledDate": "05-11-2023",
//       "fillingFrequency": "Annually",
//   },
//   {
//       "sno": 11,
//       "natureOfActivity": "Registration",
//       "activity": "Shops & Establishments",
//       "nameOfForm": "Form-S&E",
//       "applicationLaw": "Shops and Establishments Act",
//       "typeOfAct": "State",
//       "section":"data",
//       "actualFillingFrequency": "NA",
//       "lastFilledDate": "01-04-2024",
//       "fillingFrequency": "NA",
//   },
//   {
//       "sno": 12,
//       "natureOfActivity": "Nomination",
//       "activity": "Gratuity Compliance",
//       "nameOfForm": "Form-G",
//       "applicationLaw": "Payment of Gratuity Act. 1972",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "NA",
//       "lastFilledDate": "12-05-2024",
//       "fillingFrequency": "NA",
//   },
//   {
//       "sno": 13,
//       "natureOfActivity": "Audit",
//       "activity": "Labour Welfare Fund",
//       "nameOfForm": "Form-LWF",
//       "applicationLaw": "Labour Welfare Fund Act",
//       "typeOfAct": "State",
//       "section":"data",
//       "actualFillingFrequency": "Annually",
//       "lastFilledDate": "05-06-2024",
//       "fillingFrequency": "Annually",
//   },
//   {
//       "sno": 14,
//       "natureOfActivity": "Filing",
//       "activity": "Professional Tax",
//       "nameOfForm": "Form-P",
//       "applicationLaw": "Professional Tax Act",
//       "typeOfAct": "State",
//       "section":"data",
//       "actualFillingFrequency": "Half-Yearly",
//       "lastFilledDate": "15-06-2024",
//       "fillingFrequency": "Half-Yearly",
//   },
//   {
//       "sno": 15,
//       "natureOfActivity": "Return",
//       "activity": "Bonus Payment",
//       "nameOfForm": "Form-R",
//       "applicationLaw": "Payment of Bonus Act. 1965",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "Annually",
//       "lastFilledDate": "08-12-2023",
//       "fillingFrequency": "Annually",
//   },
//   {
//       "sno": 16,
//       "natureOfActivity": "Nomination",
//       "activity": "PF Compliance",
//       "nameOfForm": "Form-2/E - nomination",
//       "applicationLaw": "Provident Fund & Miscellaneous Act. 1952",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "NA",
//       "lastFilledDate": "09-08-2024",
//       "fillingFrequency": "NA",
//   },
//   {
//       "sno": 17,
//       "natureOfActivity": "Registration",
//       "activity": "Gratuity Compliance",
//       "nameOfForm": "Form-F",
//       "applicationLaw": "Payment of Gratuity Act. 1972",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "NA",
//       "lastFilledDate": "22-04-2024",
//       "fillingFrequency": "NA",
//   },
//   {
//       "sno": 18,
//       "natureOfActivity": "Declaration",
//       "activity": "Labour Welfare Fund",
//       "nameOfForm": "Form-A",
//       "applicationLaw": "Labour Welfare Fund Act",
//       "typeOfAct": "State",
//       "section":"data",
//       "actualFillingFrequency": "Annually",
//       "lastFilledDate": "12-07-2024",
//       "fillingFrequency": "Annually",
//   },
//   {
//       "sno": 19,
//       "natureOfActivity": "Return",
//       "activity": "Professional Tax",
//       "nameOfForm": "Form-II",
//       "applicationLaw": "Professional Tax Act",
//       "typeOfAct": "State",
//       "section":"data",
//       "actualFillingFrequency": "Half-Yearly",
//       "lastFilledDate": "15-06-2024",
//       "fillingFrequency": "Half-Yearly",
//   },
//   {
//       "sno": 20,
//       "natureOfActivity": "Audit",
//       "activity": "PF Compliance",
//       "nameOfForm": "Form-Audit",
//       "applicationLaw": "Provident Fund & Miscellaneous Act. 1952",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "Annually",
//       "lastFilledDate": "22-03-2024",
//       "fillingFrequency": "Annually",
//   },
//   {
//       "sno": 21,
//       "natureOfActivity": "Registration",
//       "activity": "ESI Compliance",
//       "nameOfForm": "Form-1",
//       "applicationLaw": "Employee State Insurance Act. 1948",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "Monthly",
//       "lastFilledDate": "01-08-2024",
//       "fillingFrequency": "Monthly",
//   },
//   {
//       "sno": 22,
//       "natureOfActivity": "Nomination",
//       "activity": "Gratuity Compliance",
//       "nameOfForm": "Form-G",
//       "applicationLaw": "Payment of Gratuity Act. 1972",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "NA",
//       "lastFilledDate": "12-05-2024",
//       "fillingFrequency": "NA",
//   },
//   {
//       "sno": 23,
//       "natureOfActivity": "Filing",
//       "activity": "Maternity Benefits",
//       "nameOfForm": "Form-MB",
//       "applicationLaw": "Maternity Benefit Act. 1961",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "NA",
//       "lastFilledDate": "30-07-2024",
//       "fillingFrequency": "NA",
//   },
//   {
//       "sno": 24,
//       "natureOfActivity": "Return",
//       "activity": "Bonus Payment",
//       "nameOfForm": "Form-R",
//       "applicationLaw": "Payment of Bonus Act. 1965",
//       "typeOfAct": "Central",
//       "section":"data",
//       "actualFillingFrequency": "Annually",
//       "lastFilledDate": "08-12-2023",
//       "fillingFrequency": "Annually",
//   },
//   {
//       "sno": 25,
//       "natureOfActivity": "Filing",
//       "activity": "Professional Tax",
//       "nameOfForm": "Form-P",
//       "applicationLaw": "Professional Tax Act",
//       "typeOfAct": "State",
//       "section":"data",
//       "actualFillingFrequency": "Half-Yearly",
//       "lastFilledDate": "15-06-2024",
//       "fillingFrequency": "Half-Yearly",
//   }
]
