export const ComplianceData=[
    {
      Sno: 1,
      Company_Name: 'ACME Corporation',
      Branch: 'Royapuram',
      Activity: 'PF Remittance',
      NatureofActivity:'data',
      Form_name: 'PF Challan',
      Acts: 'Provident Fund & Miscellanous Act, 1952',
      ActType: 'Central',
      state: 'NA',
      Filed_Date: '15-08-2024',
      Period: 'Sep-24',
      Document: 'Payment Receipt',
      Priority: 'High',
      Status: 'Complied',
    },
    {
      Sno: 2,
      Company_Name: 'ACME Corporation',
      Branch: 'Adayar',
      Activity: 'PF Compliance',
      NatureofActivity:'data',
      Form_name: 'Form-2',
      Acts: 'Provident Fund & Miscellanous Act, 1952',
      ActType: 'Central',
      state: 'NA',
      Filed_Date: 'NA',
      Period: 'Sep-24',
      Document: 'Preserve Form 2',
      Priority: 'Medium',
      Status: 'Complied',
    },
    {
      Sno: 3,
      Company_Name: 'ACME Corporation',
      Branch: 'Royapettah',
      Activity: 'PF Return-W',
      NatureofActivity:'data',
      Form_name: 'International Worker\'s return',
      Acts: 'Provident Fund & Miscellanous Act, 1952',
      ActType: 'Central',
      state: 'NA',
      Filed_Date: '14-08-2024',
      Period: 'Sep-24',
      Document: 'Copy of Return Submitted',
      Priority: 'Low',
      Status: 'Complied',
    },
    {
      Sno: 4,
      Company_Name: 'ACME Corporation',
      Branch: 'Mylapore',
      Activity: 'Portal compliance updating',
      NatureofActivity:'data',
      Form_name: 'Form 5 A',
      Acts: 'Employee Stote Insurance Act, 1948',
      ActType: 'Central',
      state: 'NA',
      Filed_Date: '15-08-2024',
      Period: 'Mar-24',
      Document: 'Copy of Form 5 A',
      Priority: 'High',
      Status: 'Complied',
    },
    {
      Sno: 5,
      Company_Name: 'ACME Corporation',
      Branch: 'Adayar',
      Activity: 'PF Compliance',
      NatureofActivity:'data',
      Form_name: 'PF Challan',
      Acts: 'Provident Fund & Miscellanous Act, 1952',
      ActType: 'Central',
      state: 'NA',
      Filed_Date: 'NA',
      Period: 'Sep-24',
      Document: 'NA',
      Priority: 'Low',
      Status: 'Complied',
    },
    {
      Sno: 6,
      Company_Name: 'ACME Corporation',
      Branch: 'Ambattur',
      Activity: 'PF Return-W',
      NatureofActivity:'data',
      Form_name: 'Form-2',
      Acts: 'Employee State Insurance Act, 1948',
      ActType: 'State',
      state: 'Tamil nadu',
      Filed_Date: '27-03-2024',
      Period: 'Mor-24',
      Document: 'NA',
      Priority: 'Medium',
      Status: 'Complied',
    },
    {
      Sno: 7,
      Company_Name: 'ACME Corporation',
      Branch: 'Royapattah',
      Activity: 'PF Remittance',
      NatureofActivity:'data',
      Form_name: 'International Worker\'s return',
      Acts: 'Provident Fund & Miscellanous Act, 1952',
      ActType: 'State',
      state: 'Tamil nadu',
      Filed_Date: 'NA',
      Period: 'Mor-24',
      Document: 'Not Applicable',
      Priority: 'High',
      Status: 'Complied',
    },
    {
      Sno: 8,
      Company_Name: 'ACME Corporation',
      Branch: 'Ambattur',
      Activity: 'PF Return-W',
      NatureofActivity:'data',
      Form_name: 'Form-2',
      Acts: 'Employee State Insurance Act, 1948',
      ActType: 'State',
      state: 'Tamil nadu',
      Filed_Date: '04-04-2024',
      Period: 'Mor-24',
      Document: 'Form II copy',
      Priority: 'High',
      Status: 'Complied',
    },
    {
      Sno: 9,
      Company_Name: 'ACME Corporation',
      Branch: 'Royapettah',
      Activity: 'PF Remittance',
      NatureofActivity:'data',
      Form_name: 'PF Challan',
      Acts: 'Provident Fund & Miscellanous Act, 1952',
      ActType: 'State',
      state: 'Tamil nadu',
      Filed_Date: '15-07-2024',
      Period: 'NA',
      Document: 'Not Applicable',
      Priority: 'Medium',
      Status: 'Complied',
    },
    {
      Sno: 10,
      Company_Name: 'ACME Corporation',
      Branch: 'Adayar',
      Activity: 'PF Return-W',
      NatureofActivity:'data',
      Form_name: 'International Worker\'s return',
      Acts: 'Employee Sto Insurance Act. 1948',
      ActType: 'State',
      state: 'Tamil nadu',
      Filed_Date: 'NA',
      Period: 'NA',
      Document: 'PT Registration Certificate',
      Priority: 'Low',
      Status: 'Complied',
    },
    {
        Sno: 1,
        Company_Name: 'ACME Corporation',
        Branch: 'Royapuram',
        Activity: 'PF Remittance',
        NatureofActivity:'data',
        Form_name: 'PF Challan',
        Acts: 'Provident Fund & Miscellanous Act, 1952',
        ActType: 'Central',
        state: 'NA',
        Filed_Date: '15-08-2024',
        Period: 'Sep-24',
        Document: 'Payment Receipt',
        Priority: 'High',
        Status: 'Complied',
      },
      {
        Sno: 2,
        Company_Name: 'ACME Corporation',
        Branch: 'Adayar',
        Activity: 'PF Compliance',
        NatureofActivity:'data',
        Form_name: 'Form-2',
        Acts: 'Provident Fund & Miscellanous Act, 1952',
        ActType: 'Central',
        state: 'NA',
        Filed_Date: 'NA',
        Period: 'Sep-24',
        Document: 'Preserve Form 2',
        Priority: 'Medium',
        Status: 'Complied',
      },
      {
        Sno: 3,
        Company_Name: 'ACME Corporation',
        Branch: 'Royapettah',
        Activity: 'PF Return-W',
        NatureofActivity:'data',
        Form_name: 'International Worker\'s return',
        Acts: 'Provident Fund & Miscellanous Act, 1952',
        ActType: 'Central',
        state: 'NA',
        Filed_Date: '14-08-2024',
        Period: 'Sep-24',
        Document: 'Copy of Return Submitted',
        Priority: 'Low',
        Status: 'Complied',
      },
      {
        Sno: 4,
        Company_Name: 'ACME Corporation',
        Branch: 'Mylapore',
        Activity: 'Portal compliance updating',
        NatureofActivity:'data',
        Form_name: 'Form 5 A',
        Acts: 'Employee Stote Insurance Act, 1948',
        ActType: 'Central',
        state: 'NA',
        Filed_Date: '15-08-2024',
        Period: 'Mar-24',
        Document: 'Copy of Form 5 A',
        Priority: 'High',
        Status: 'Complied',
      },
      {
        Sno: 5,
        Company_Name: 'ACME Corporation',
        Branch: 'Adayar',
        Activity: 'PF Compliance',
        NatureofActivity:'data',
        Form_name: 'PF Challan',
        Acts: 'Provident Fund & Miscellanous Act, 1952',
        ActType: 'Central',
        state: 'NA',
        Filed_Date: 'NA',
        Period: 'Sep-24',
        Document: 'NA',
        Priority: 'Low',
        Status: 'Complied',
      },
      {
        Sno: 6,
        Company_Name: 'ACME Corporation',
        Branch: 'Ambattur',
        Activity: 'PF Return-W',
        NatureofActivity:'data',
        Form_name: 'Form-2',
        Acts: 'Employee State Insurance Act, 1948',
        ActType: 'State',
        state: 'Tamil nadu',
        Filed_Date: '27-03-2024',
        Period: 'Mor-24',
        Document: 'NA',
        Priority: 'Medium',
        Status: 'Complied',
      },
      {
        Sno: 7,
        Company_Name: 'ACME Corporation',
        Branch: 'Royapattah',
        Activity: 'PF Remittance',
        NatureofActivity:'data',
        Form_name: 'International Worker\'s return',
        Acts: 'Provident Fund & Miscellanous Act, 1952',
        ActType: 'State',
        state: 'Tamil nadu',
        Filed_Date: 'NA',
        Period: 'Mor-24',
        Document: 'Not Applicable',
        Priority: 'High',
        Status: 'Complied',
      },
      {
        Sno: 8,
        Company_Name: 'ACME Corporation',
        Branch: 'Ambattur',
        Activity: 'PF Return-W',
        NatureofActivity:'data',
        Form_name: 'Form-2',
        Acts: 'Employee State Insurance Act, 1948',
        ActType: 'State',
        state: 'Tamil nadu',
        Filed_Date: '04-04-2024',
        Period: 'Mor-24',
        Document: 'Form II copy',
        Priority: 'High',
        Status: 'Complied',
      },
      {
        Sno: 9,
        Company_Name: 'ACME Corporation',
        Branch: 'Royapettah',
        Activity: 'PF Remittance',
        NatureofActivity:'data',
        Form_name: 'PF Challan',
        Acts: 'Provident Fund & Miscellanous Act, 1952',
        ActType: 'State',
        state: 'Tamil nadu',
        Filed_Date: '15-07-2024',
        Period: 'NA',
        Document: 'Not Applicable',
        Priority: 'Medium',
        Status: 'Complied',
      },
      {
        Sno: 10,
        Company_Name: 'ACME Corporation',
        Branch: 'Adayar',
        Activity: 'PF Return-W',
        NatureofActivity:'data',
        Form_name: 'International Worker\'s return',
        Acts: 'Employee Sto Insurance Act. 1948',
        ActType: 'State',
        state: 'Tamil nadu',
        Filed_Date: 'NA',
        Period: 'NA',
        Document: 'PT Registration Certificate',
        Priority: 'Low',
        Status: 'Complied',
      }
]
