const data =  [
    {
        "sno": "1",
        "company": "Company 1 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 1",
        "compliance": "Trade License",
        "assignstaff": "Ashok",
        "priority": "Low",
        "score": "1",
        "status": "Over Due"
    },
    {
        "sno": "2",
        "company": "Company 2 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 2",
        "compliance": "PF Remittance",
        "assignstaff": "Ashok",
        "priority": "Medium",
        "score": "2",
        "status": "Over Due"
    },
    {
        "sno": "3",
        "company": "Company 3 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 3",
        "compliance": "Trade License",
        "assignstaff": "Swetha",
        "priority": "Low",
        "score": "3",
        "status": "Not Complied"
    },
    {
        "sno": "4",
        "company": "Company 4 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 4",
        "compliance": "PF Remittance",
        "assignstaff": "Ashok",
        "priority": "Medium",
        "score": "4",
        "status": "Complied"
    },
    {
        "sno": "5",
        "company": "Company 5 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 5",
        "compliance": "Trade License",
        "assignstaff": "Ashok",
        "priority": "High",
        "score": "5",
        "status": "Over Due"
    },
    {
        "sno": "6",
        "company": "Company 6 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 6",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "Medium",
        "score": "6",
        "status": "Not Complied"
    },
    {
        "sno": "7",
        "company": "Company 7 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 7",
        "compliance": "Trade License",
        "assignstaff": "Ashok",
        "priority": "Low",
        "score": "7",
        "status": "Over Due"
    },
    {
        "sno": "8",
        "company": "Company 8 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 8",
        "compliance": "PF Remittance",
        "assignstaff": "Ashok",
        "priority": "Medium",
        "score": "8",
        "status": "Complied"
    },
    {
        "sno": "9",
        "company": "Company 9 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 9",
        "compliance": "Trade License",
        "assignstaff": "Swetha",
        "priority": "Low",
        "score": "9",
        "status": "Not Complied"
    },
    {
        "sno": "10",
        "company": "Company 10 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 10",
        "compliance": "PF Remittance",
        "assignstaff": "Ashok",
        "priority": "High",
        "score": "0",
        "status": "Over Due"
    },
    {
        "sno": "11",
        "company": "Company 11 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 11",
        "compliance": "Trade License",
        "assignstaff": "Ashok",
        "priority": "Low",
        "score": "1",
        "status": "Over Due"
    },
    {
        "sno": "12",
        "company": "Company 12 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 12",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "Medium",
        "score": "2",
        "status": "Complied"
    },
    {
        "sno": "13",
        "company": "Company 13 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 13",
        "compliance": "Trade License",
        "assignstaff": "Ashok",
        "priority": "Low",
        "score": "3",
        "status": "Over Due"
    },
    {
        "sno": "14",
        "company": "Company 14 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 14",
        "compliance": "PF Remittance",
        "assignstaff": "Ashok",
        "priority": "Medium",
        "score": "4",
        "status": "Over Due"
    },
    {
        "sno": "15",
        "company": "Company 15 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 15",
        "compliance": "Trade License",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "5",
        "status": "Not Complied"
    },
    {
        "sno": "16",
        "company": "Company 16 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 16",
        "compliance": "PF Remittance",
        "assignstaff": "Ashok",
        "priority": "Medium",
        "score": "6",
        "status": "Complied"
    },
    {
        "sno": "17",
        "company": "Company 17 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 17",
        "compliance": "Trade License",
        "assignstaff": "Ashok",
        "priority": "Low",
        "score": "7",
        "status": "Over Due"
    },
    {
        "sno": "18",
        "company": "Company 18 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 18",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "Medium",
        "score": "8",
        "status": "Not Complied"
    },
    {
        "sno": "19",
        "company": "Company 19 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 19",
        "compliance": "Trade License",
        "assignstaff": "Ashok",
        "priority": "Low",
        "score": "9",
        "status": "Over Due"
    },
    {
        "sno": "20",
        "company": "Company 20 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 20",
        "compliance": "PF Remittance",
        "assignstaff": "Ashok",
        "priority": "High",
        "score": "0",
        "status": "Complied"
    },
    {
        "sno": "21",
        "company": "Company 21 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 21",
        "compliance": "Trade License",
        "assignstaff": "Swetha",
        "priority": "Low",
        "score": "1",
        "status": "Not Complied"
    },
    {
        "sno": "22",
        "company": "Company 22 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 22",
        "compliance": "PF Remittance",
        "assignstaff": "Ashok",
        "priority": "Medium",
        "score": "2",
        "status": "Over Due"
    },
    {
        "sno": "23",
        "company": "Company 23 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 23",
        "compliance": "Trade License",
        "assignstaff": "Ashok",
        "priority": "Low",
        "score": "3",
        "status": "Over Due"
    },
    {
        "sno": "24",
        "company": "Company 24 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 24",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "Medium",
        "score": "4",
        "status": "Complied"
    },
    {
        "sno": "25",
        "company": "Company 25 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 25",
        "compliance": "Trade License",
        "assignstaff": "Ashok",
        "priority": "High",
        "score": "5",
        "status": "Over Due"
    },
    {
        "sno": "26",
        "company": "Company 26 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 26",
        "compliance": "PF Remittance",
        "assignstaff": "Ashok",
        "priority": "Medium",
        "score": "6",
        "status": "Over Due"
    },
    {
        "sno": "27",
        "company": "Company 27 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 27",
        "compliance": "Trade License",
        "assignstaff": "Swetha",
        "priority": "Low",
        "score": "7",
        "status": "Partially Complied"
    },
    {
        "sno": "28",
        "company": "Company 28 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 28",
        "compliance": "PF Remittance",
        "assignstaff": "Ashok",
        "priority": "Medium",
        "score": "8",
        "status": "Complied"
    },
    {
        "sno": "29",
        "company": "Company 29 Technologies India Private Limited",
        "state": "Maharashtra",
        "branch": "Branch 29",
        "compliance": "Trade License",
        "assignstaff": "Ashok",
        "priority": "Low",
        "score": "9",
        "status": "Over Due"
    },
    {
        "sno": "30",
        "company": "Company 30 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 30",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "4",
        "status": "Not Complied"
    },
    {
        "sno": "31",
        "company": "Company 30 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 30",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "0",
        "status": "Partially Complied"
    },
    {
        "sno": "32",
        "company": "Company 30 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 30",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "0",
        "status": "Partially Complied"
    },
    {
        "sno": "33",
        "company": "Company 30 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 30",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "0",
        "status": "Partially Complied"
    },
    {
        "sno": "33",
        "company": "Company 30 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 30",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "0",
        "status": "Partially Complied"
    },
    {
        "sno": "33",
        "company": "Company 30 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 30",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "0",
        "status": "Partially Complied"
    },
    {
        "sno": "33",
        "company": "Company 30 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 30",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "0",
        "status": " Complied"
    },
    {
        "sno": "33",
        "company": "Company 30 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 30",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "0",
        "status": "Partially Complied"
    },
    {
        "sno": "33",
        "company": "Company 30 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 30",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "0",
        "status": "Not Complied"
    },
    {
        "sno": "33",
        "company": "Company 30 Technologies India Private Limited",
        "state": "Tamil Nadu",
        "branch": "Branch 30",
        "compliance": "PF Remittance",
        "assignstaff": "Swetha",
        "priority": "High",
        "score": "0",
        "status": "Complied"
    }
]
export default data